#!/bin/bash

usage () {
    echo "usage: meet [title]"
}

# if no arguments are given, print usage and exit
[[ -z "$*" ]] && usage && exit 1;

current_date=$(date +%F)
title="$*"
slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '_')
filename="${current_date}_${slug}.md"

NOTES_DIR="$HOME/notes";
TEMPLATE_DIR="$HOME/notes/.templates";

mkdir -p "$NOTES_DIR"
mkdir -p "$TEMPLATE_DIR"

cd "$NOTES_DIR"

# if filename already exists, warn and exit
[[ -f "$filename" ]] && echo "WARNING: $filename already exists" && exit 1

template_path="$TEMPLATE_DIR/meeting"
template=$(cat "$template_path" | tpl)

echo "$template" >> "$filename" && $EDITOR -c "norm Go" "$filename"


