#!/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(fd . ~/projects -td -d2 --min-depth 2 |\
    awk -F/ '{print $(NF-2)"/"$(NF-1)}' |\
    fzf-tmux -p)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected="$HOME/projects/$selected"

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

# make sure the target session exists
if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
  tmux attach -t $selected_name
else
  tmux switch-client -t $selected_name 
fi

